---
- name: Creates director
  file:
    path: "~/udacity"
    state: "directory"
    mode: 0755

- name: Copy compressed backend folder
  copy:
    src: "/backend/artifact.tar.gz"
    dest: "~/udacity/artifact.tar.gz"

- name: Extract backend
  unarchive:
    remote_src: yes
    src: "~/udacity/artifact.tar.gz"
    dest: "~/udacity"

- name: Run the web server
  shell:
    cmd: |
      cd ~/udacity
      npm install
      pm2 stop default
      pm2 start npm -- start --wait-ready