---
- name: "install npm."
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "Creates directory"
  file:
    path: "~/udacity"
    state: "directory"
    mode: 0755

- name: "Copy compressed backend folder"
  copy:
    src: "artifact-backend.tar.gz"
    dest: "~/udacity/artifact-backend.tar.gz"

- name: "Extract backend"
  unarchive:
    remote_src: yes
    src: "~/server/artifact-backend.tar.gz"
    dest: "~/server"

- name: "Run the web server"
  shell:
    cmd: |
      cd ~/server
      pm2 stop default
      pm2 start npm -- start --wait-ready