---
- name: "install npm."
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: Stop PM2 default process
  shell: pm2 stop default
  args:
    executable: /bin/bash

- name: Start PM2 npm process
  shell: pm2 start npm -- start
  args:
    executable: /bin/bash